# release/action.yml

name: Release

description: 'Release version'

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: yarn
      shell: bash

    - name: Configure committer
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
      shell: bash

    - name: Refresh branch
      run: |
        git checkout release
        git pull
      shell: bash

    - name: Semantic versioning
      run: yarn ci:release
      shell: bash

    - name: Tag release
      run: git push --follow-tags origin release
      shell: bash
