# postpublish/action.yml

name: Post publish

description: 'Clean repository'

runs:
  using: 'composite'

  steps:
    - name: get latest 'main'
      run: |
        git checkout main
        git pull
      shell: bash

    - name: Update branch 'prerelease'
      run: |
        git checkout prerelease
        git merge main
      shell: bash

    - name: Update branch 'release'
      run: |
        git checkout release
        git merge main
      shell: bash
