# postpublish/action.yml

name: Post publish

description: 'Clean repository'

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v3

    - name: Configure committer
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
      shell: bash

    - name: Merge 'main' in 'prerelease'
      run: |
        git fetch --unshallow
        git checkout prerelease
        git pull
        git merge --no-ff main -m "Auto-merge main back to prerelease"
        git push
      shell: bash

    - name: Merge 'main' in 'release'
      run: |
        git fetch --unshallow
        git checkout release
        git pull
        git merge --no-ff main -m "Auto-merge main back to release"
        git push
      shell: bash
