# publish/action.yml

name: Publish

description: 'Publish package to npmjs.org'

inputs:
  npm_token:
    required: true
    description: 'Access token for publishing packages to npm'

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: yarn
      shell: bash

    - name: Build
      run: yarn ci:build
      shell: bash

    - name: ====== DEBUG ======
      run: echo ${{ inputs.npm_token }}
      shell: bash

    - name: Publish
      run: npm publish
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
